update connectors with mux handlers to use normal in connections yaml
MarioRial22/aws-athena-query-federation pull request #17
Opened 2024-09-23 21:56 UTC by aimethed

Change all connectors that currently use the MuxCompositeHandler as the entrypoint to use the ImageConfig property to use the MuxCompositeHandler in the legacy and the CompositeHandler in the connections yaml.

2024-09-23 21:57 UTC, burhan94 approved these changes

2024-09-23 21:59 UTC, burhan94 requested changes

2024-09-23 21:59 UTC, burhan94 commented on athena-mysql/athena-mysql-connection.yaml
> +        Command: [ "com.amazonaws.athena.connectors.mysql.MySqlMuxCompositeHandler" ]
this should be non-mux right

2024-09-23 22:04 UTC, aimethed commented on athena-mysql/athena-mysql-connection.yaml
> +        Command: [ "com.amazonaws.athena.connectors.mysql.MySqlMuxCompositeHandler" ]
Yup, thanks for the catch :)

2024-09-23 22:06 UTC, burhan94 approved these changes

2024-09-24 14:25 UTC, mschoeni1 approved these changes

2024-09-24 14:25 UTC, merged